# Generated by Django 5.2.4 on 2025-07-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patologias', to='nutricion.dieta')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneacionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tiempos_comida', models.CharField(max_length=50)),
                ('platillo_fuerte', models.CharField(max_length=100)),
                ('postre', models.CharField(max_length=100)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeaciones', to='nutricion.dieta')),
            ],
        ),
    ]
